//TRY AND CATCH FUNCTIONALITY

try {
    let a=10,b=0;
    let c=a/b;
    console.log(c);
    //console1.log(d);
    //console1.log(c);
    console.log("Hey");
    
}
   catch(err) {
    console.log(err.message);
}
